# Generated by Django 2.2.1 on 2019-08-03 05:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('parcelkey', models.CharField(max_length=26)),
                ('ownerid', models.CharField(max_length=30)),
                ('registered', models.CharField(max_length=50)),
                ('eastparcel', models.CharField(max_length=50)),
                ('westparcel', models.CharField(max_length=50)),
                ('northparce', models.CharField(max_length=50)),
                ('southparce', models.CharField(max_length=50)),
                ('parcelnoen', models.BigIntegerField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
